version: "3.8"  # optional since v1.27.0
services:
  postgresqls:
    container_name: "postgresqlpostgis"
    image: "postgis/postgis:16-3.4-alpine"
    ports: 
      - "5433:5432"
    volumes:
       - db_persdata:/var/lib/postgrespers
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - default
  
  pgAdmin4:
    container_name: pgAdmin4-interface
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: pgadmin4
    depends_on: 
      - postgres
    ports:
      - 8080:80
    networks:
      network-banco:
        ipv4_address: 174.20.0.3

networks:
  network-banco:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 174.20.0.0/24